# Generated by Django 4.1.5 on 2023-01-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTCUSExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_period_start', models.CharField(blank=True, max_length=200)),
                ('time_period_end', models.CharField(blank=True, max_length=200)),
                ('time_open', models.CharField(blank=True, max_length=200)),
                ('time_close', models.CharField(blank=True, max_length=200)),
                ('rate_open', models.CharField(blank=True, max_length=200)),
                ('rate_high', models.CharField(blank=True, max_length=200)),
                ('rate_low', models.CharField(blank=True, max_length=200)),
                ('rate_close', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'BTC US Exchange',
                'verbose_name_plural': 'BTC US Exchange',
            },
        ),
    ]
