# Generated by Django 4.1.5 on 2023-01-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcusexchange',
            name='rate_close',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='btcusexchange',
            name='rate_high',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='btcusexchange',
            name='rate_low',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='btcusexchange',
            name='rate_open',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='btcusexchange',
            name='time_close',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='btcusexchange',
            name='time_open',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='btcusexchange',
            name='time_period_end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='btcusexchange',
            name='time_period_start',
            field=models.DateTimeField(),
        ),
    ]
