# Generated by Django 4.1.5 on 2023-01-12 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_btcusexchange_rate_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='btcusexchange',
            name='rate_close',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='btcusexchange',
            name='rate_high',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='btcusexchange',
            name='rate_low',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='btcusexchange',
            name='rate_open',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
